### ISSUE TITLE
Monero transaction library fails intermittently

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#166]
This has now happened three times, all within the last week or so. The first two happened at the same time when doing a lot of CI work, so I had hoped GitHub had simply killed monerod for resource use. The issue with that idea is that GitHub kills tasks, not processes in tasks. It also happened again now, when running 2 CI runs at once, yet I do believe there's an intermittent error here. I'm not sure what it is.

https://github.com/serai-dex/serai/actions/runs/3467617451/jobs/5792656820

```
running 4 tests
test multisig_send_single_input ... FAILED
test multisig_send_multiple_inputs ... ok
test send_multiple_inputs ... ok
test send_single_input ... ok

failures:

---- multisig_send_single_input stdout ----
thread 'multisig_send_single_input' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidTransaction([136, 197, 242, 44, 231, 80, 252, 242, 23, 116, 110, 33, 18, 209, 131, 116, 88, 125, 52, 161, 46, 157, 86, 61, 158, 2, 251, 107, 171, 201, 45, 6])', coins/monero/tests/send.rs:170:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'multisig_send_single_input' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1), ...)', coins/monero/tests/send.rs:186:1


failures:
    multisig_send_single_input
```

https://github.com/serai-dex/serai/actions/runs/3467617445/jobs/5792656679

```
running 2 tests
test send_single_input ... FAILED
test send_multiple_inputs ... ok

failures:

error: test failed, to rerun pass `-p monero-serai --test send`
---- send_single_input stdout ----
thread 'send_single_input' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidTransaction([7, 109, 70, 203, 226, 122, 224, 109, 213, 70, 45, 209, 43, 106, 51, 77, 245, 208, 147, 45, 138, 87, 251, 40, 147, 241, 157, 196, 54, 75, 9, 236])', coins/monero/tests/send.rs:170:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'send_single_input' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1), ...)', coins/monero/tests/send.rs:175:1


failures:
    send_single_input
```

https://github.com/serai-dex/serai/actions/runs/3532160089/jobs/5926174022

```
failures:

---- multisig_send_single_input stdout ----
thread 'multisig_send_single_input' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidTransaction([254, 69, 221, 202, 43, 168, 249, 55, 186, 16, 152, 151, 98, 58, 60, 239, 246, 147, 191, 185, 110, 167, 144, 251, 30, 238, 12, 87, 207, 147, 174, 118])', coins/monero/tests/send.rs:170:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'multisig_send_single_input' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(10), ...)', coins/monero/tests/send.rs:186:1


failures:
    multisig_send_single_input
```

**Comment by kayabaNerve** [comment]
The immediate way to begin debugging would likely be to obtain a copy of the monerod logs form such a transaction. That'd help narrow done which component is failing. Moving the tests over to a seeded RNG may also be beneficial (that probably deserves its own issue...).

**Comment by kayabaNerve** [comment]
I wonder if it could be the Monero node running out of disk space. The parallel run now I was going failed for that reason.

**Comment by kayabaNerve** [comment]
https://github.com/serai-dex/serai/actions/runs/3532275588/jobs/5935263778

**Comment by kayabaNerve** [comment]
"help resolve 166" matched as "resolve 166".

The Monero lib should not have a new version published until this is corrected.

**Comment by kayabaNerve** [comment]
```
[coins/monero/src/rpc.rs:476] res = SendRawResponse {
    status: "Failed",
    double_spend: false,
    fee_too_low: false,
    invalid_input: true,
    invalid_output: false,
    low_mixin: false,
    not_relayed: false,
    overspend: false,
    too_big: false,
    too_few_outputs: false,
    reason: "",
}
thread 'multisig_send_single_input' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidTransaction([166, 181, 121, 70, 132, 77, 71, 105, 68, 182, 224, 134, 252, 4, 220, 230, 7, 18, 253, 94, 108, 164, 0, 161, 254, 63, 200, 147, 133, 184, 179, 88])', coins/monero/tests/send.rs:170:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'multisig_send_single_input' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1), ...)', coins/monero/tests/send.rs:186:1
```

Confirmed we're producing faulty transactions. This is probably to do with the CLSAG. I have no idea why and cannot think of any recent changes which would cause intermittent failures to both single signer and multisig. I'll have to review that.

**Comment by kayabaNerve** [comment]
https://github.com/serai-dex/serai/actions/runs/3538700723/jobs/5939789499

**Comment by kayabaNerve** [comment]
Cannot repro locally. Making a dedicated branch to push debug code.

**Comment by kayabaNerve** [comment]
I currently believe this is most likely some race conditions rather than any legitimate cryptographic error.

**Comment by kayabaNerve** [comment]
akil has been able to locally replicate this. Their explicit reason was the input wasn't old enough, and the TX which should be in block 91 is actually in block 92. It happens more often on low powered machines, yet those failed to replicate when `set_log 2` was set.
