### ISSUE TITLE
Monero seed test failed in CI

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#478]
https://github.com/serai-dex/serai/actions/runs/7139662256/job/19443422741

```
failures:

---- tests::seed::test_classic_seed stdout ----
thread 'tests::seed::test_classic_seed' panicked at coins/monero/src/tests/seed.rs:180:88:
called `Result::unwrap()` on an `Err` value: InvalidChecksum
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1077:23
   4: monero_serai::tests::seed::test_classic_seed
             at ./src/tests/seed.rs:180:24
   5: monero_serai::tests::seed::test_classic_seed::{{closure}}
             at ./src/tests/seed.rs:17:24
   6: core::ops::function::FnOnce::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    tests::seed::test_classic_seed

test result: FAILED. 17 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.48s

error: test failed, to rerun pass `-p monero-serai --lib`
```

**Comment by j-berman** [comment]
Where I'm at with this...

It's panicking in `seed.entropy()` in the second print statement from #487, so the failing seed doesn't actually print:

https://github.com/serai-dex/serai/blob/74a68c6f68e5fe0cacd69981b8081e49ab5f50b4/coins/monero/src/tests/seed.rs#L188-L193

Here are some failing seeds:

`nouer azur ailleurs masque descendre morose lion roche position supposer haine camion tome retrouver monsieur sapin jauge casque toast galet neutre larve nuage occuper lion`

`ottobre amore fisico soffitto fissare incanto filosofo citofono cabina cantare bufera assegno temere jazz ampliare pietra spiegare togliere menta gancio dominare equivoco ignoto invocare cabina`

`africano paradiso digitare sabbia fuso proteina febbre atlante iniziare ricambio spazio reattore algebra stallone richiamo malloppo governo ragazza indotto bancomat natura arrivare digerire dormire atlante`

EDIT: copied the wrong failing spot

**Comment by j-berman** [comment]
A failing seed that I confirmed succeeds in the CLI and https://xmr.llcoins.net/ :

```
    Vector {
      language: classic::Language::Spanish,
      seed: "pluma laico atraer pintor peor cerca balde buscar \
               lancha batir nulo reloj resto gemelo nevera poder columna gol \
               oveja latir amplio bolero feliz fuerza nevera"
        .into(),
      spend: "30303983fc8d215dd020cc6b8223793318d55c466a86e4390954f373fdc7200a".into(),
      view: "97c649143f3c147ba59aa5506cc09c7992c5c219bb26964442142bf97980800e".into(),
    }
```

**Comment by j-berman** [comment]
~~Looks like the problem arises from having a duplicate word to the checksum~~

Ignore. Not the issue/is expected.
